### ISSUE TITLE
[bug] SmartScreen warning when launching the installer on Windows 10

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#235] opened 2024-08-12 12:34 UTC
When you first try to launch the installer on Windows 10, SmartScreen prevents it from running because it does not recognise the file's publisher or signature. The SmartScreen popup shows the publisher is "Unknown Publisher" so that may have something to do with it.

**Comment by millerjp** [comment] 2024-08-12 13:45
@rgooding this is a duplicate of #43 . This should be resolved once the github pipline is signing. I will leave this open though as @digiserg will need you to retest it once he does it.

**Closed** 2024-08-29 08:49 UTC
Labels: Windows, build
