### ISSUE TITLE
[bug]: Executing "select * system.compaction_history;" in notebook view does not display any rows

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#393] opened 2024-09-10 15:02 UTC
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

1.0.0-beta-20240910-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### Operating System Version

Windows 11

### Apache Cassandra Version(s)

5.0.0

### Bug Description

Running the above query in the terminal view shows some rows.
![image](https://github.com/user-attachments/assets/74b3a3da-a1dd-4eb8-9241-242384eacb24)

Notebook view shows none.
![image](https://github.com/user-attachments/assets/0eba3ff7-22a0-4fdb-8190-9d5a604ee14d)

### Steps to Reproduce

Execute "select * from system.compaction_history;" in notebook view.

### Expected Behavior

Executing the query should show some rows.

### Actual Behavior

Executing the query shows no rows.

### Severity

High

**Comment by millerjp** [comment] 2024-09-10 16:23
@mhmdkrmabd I have tested this on MacOs v1.0.0-beta-20240909-01 and it returns ok

**Comment by hshimizu** [comment] 2024-09-10 16:56
![image](https://github.com/user-attachments/assets/91f3d25d-4648-45e5-b40e-5b442e578f71)

**Comment by millerjp** [comment] 2024-09-10 16:59
@mhmdkrmabd It looks like its specific to this table  and its data times and windows

**Comment by mhmdkrmabd** [comment] 2024-09-10 17:38
@millerjp @hshimizu confirmed this bug, only happen on Windows 10, not confirmed yet if it's only for the table `system.compaction_history;` or it's about the data type in it
![image](https://github.com/user-attachments/assets/fd77e99a-d552-4b03-a7b2-0dfa36ac45f0)

**Comment by digiserg** [comment] 2024-09-11 10:40
Fixed in the latest beta

**Comment by digiserg** [comment] 2024-09-11 13:38
@mhmdkrmabd I'm reopening this issue 

Uploading Screen Recording 2024-09-11 at 14.35.09.mov…

as it seems to happen still but not always. I get the problem always the first time though. See video.

**Closed** 2024-09-23 09:39 UTC
Labels: Bug, cql console
