### ISSUE TITLE
Test Connection hangs forever on Deb Linux

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#109] opened 2024-07-16 09:08 UTC
Testing on Debian 12 amd64.
I have a Cassandra server running at 127.0.0.1:9042. In the Add Cluster dialog I have entered the DC, hostname, port, username and password correctly but when I click `Test Connection` I am shown an animation and nothing else seems to happen. The app just hangs here.
cqlsh is able to connect from the command-line using the same connection details.

**Comment by digiserg** [comment] 2024-07-16 09:20
@rgooding is this in Linux? Did you use the python cqlsh or the cqlsh binary we distribute to test the connection?

**Comment by mhmdkrmabd** [comment] 2024-07-16 11:37
@digiserg I've mentioned in the channel that `cqlsh-407` is not working, it's the used binary to test connection, please consider to give it a try, it seems in the building process the version for Linux is missing, that's the cause of the issue

![Image](https://github.com/user-attachments/assets/bcee9fcd-d06e-4690-84ba-cf290beae5cf)

**Comment by mhmdkrmabd** [comment] 2024-07-16 11:37
I'll move this to be reviewed

**Comment by digiserg** [comment] 2024-07-16 12:47
`cqlsh` works fine for me using the latest version. `keys_generator` does not in my test VM 

https://github.com/axonops/axonops-workbench-cassandra/issues/118

**Comment by mhmdkrmabd** [comment] 2024-07-16 13:02
@digiserg 
![image](https://github.com/user-attachments/assets/f18f3835-dfaf-4771-8468-2451e4af4982)
![image](https://github.com/user-attachments/assets/bfc07045-6207-4e31-a5e4-3ff7d49f879b)

**Comment by digiserg** [comment] 2024-07-16 13:49
ah, sorry, I misunderstood you. 
The problem is pretty silly, the `curl`  command returns 404. 
https://github.com/axonops/axonops-workbench-cassandra/blob/main/.github/workflows/release.yml#L57

I'll sort it out.

**Comment by digiserg** [comment] 2024-07-16 14:49
@mhmdkrmabd fixed in this build. If you can test it, we can close the ticket

https://github.com/axonops/axonops-workbench-cassandra/releases/tag/0.1.0-internal-20240716

**Comment by mhmdkrmabd** [comment] 2024-07-16 18:23
@digiserg tested `cqlsh-407` in the latest build, works fine now
![image](https://github.com/user-attachments/assets/6629629c-ad46-420e-b75a-4886b366abcd)

**Closed** 2024-07-17 07:42 UTC
Labels: bug, Linux, almost completed, cql console
